name: Photography_LB
favicon: null
layout_spectrum: 0.6012413073331118
typography_spectrum: 0.20258524315431714
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76727504-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6049872296862304
  lightness: 0.8535881394054741
  saturation: 0.15361296641640365
  rhythmicContrast: 0.8272773043718189
purpose: []
