name: Lyle Baer Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.90232
title: Photography by Lyle Baer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76727504-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6a5741'
    - '#a09d90'
    - '#4678cb'
    - '#dcd6c2'
    - '#23314e'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
